name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        apt-get update -y
        apt-get install libdbus-glib-1-dev
        cargo build --verbose
